import asyncio
from pathlib import Path
import numpy as np
import pandas as pd
from src.search.interfaces import DBResultItem, ProductMetadata

# Define relative paths to the outputs generated by stage1
DATA_DIR = Path(__file__).resolve().parent.parent / "models" / "embeddings"
print(DATA_DIR)
EMBEDDINGS_PATH = DATA_DIR / "office_products_micro_embeddings_fp32.npy"
METADATA_PATH = DATA_DIR / "office_products_micro.parquet"

# Global indicators to serve as our in-memory data tables
_embeddings: np.ndarray = None
_metadata_df: pd.DataFrame = None


def _init_data_cache():
    """Lazy loader to pull matrices into RAM on the first query request."""
    global _embeddings, _metadata_df
    if _embeddings is None or _metadata_df is None:
        if not EMBEDDINGS_PATH.exists() or not METADATA_PATH.exists():
            raise FileNotFoundError(
                f"Data artifacts missing! Run embedding pipeline first or check paths.\n"
                f"Expected metadata at: {METADATA_PATH}"
            )
        _embeddings = np.load(str(EMBEDDINGS_PATH))
        _metadata_df = pd.read_parquet(str(METADATA_PATH))
        print(f"Simulator successfully cached {_embeddings.shape[0]} real rows into RAM.")


class RealDataLocalSimulator:
    @staticmethod
    async def search_sparse(query: str, limit: int = 10) -> list[DBResultItem]:
        """Simulates Postgres keyword matching using simple case-insensitive text matching."""
        _init_data_cache()
        await asyncio.sleep(0.02)  # artificial I/O delay

        # Approximate BM25 keyword matching by looking for query words in title/categories
        tokens = query.lower().split()
        if not tokens:
            return []

        # Compute a simple phrase/keyword match hit count as a placeholder score
        matches = []
        for idx, row in _metadata_df.iterrows():
            title_text = str(row.get("title", "")).lower()
            store_text = str(row.get("store", "")).lower()

            score = sum(1.0 for token in tokens if token in title_text or token in store_text)
            if score > 0:
                matches.append((idx, score))

        # Sort by match counts descending
        matches = sorted(matches, key=lambda x: x[1], reverse=True)[:limit]

        results = []
        for idx, score in matches:
            row = _metadata_df.iloc[idx]
            results.append(DBResultItem(
                product_id=str(row["parent_asin"]),
                score=float(score),
                metadata=ProductMetadata(**row.to_dict())
            ))
        return results

    @staticmethod
    async def search_dense(query_vector: list[float], limit: int = 10) -> list[DBResultItem]:
        """Calculates true cosine similarity using a NumPy matrix dot product."""
        _init_data_cache()
        await asyncio.sleep(0.03)  # artificial I/O delay

        q_vec = np.array(query_vector, dtype=np.float32)

        # Matrix multiplication: (N, 384) x (384,) -> (N,) scores
        # Since teammate vectors are already L2 normalized, dot product IS cosine similarity
        scores = _embeddings @ q_vec

        # Get indices of top sorted elements
        top_indices = np.argsort(scores)[::-1][:limit]

        results = []
        for idx in top_indices:
            row = _metadata_df.iloc[idx]
            results.append(DBResultItem(
                product_id=str(row["parent_asin"]),
                score=float(scores[idx]),
                metadata=ProductMetadata(**row.to_dict())
            ))
        return results